import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Instrument_Serif } from "next/font/google";
import { Instrument_Sans } from "next/font/google";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument-serif",
  weight: "400",
});
const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-instrument-sans",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSerif.variable}`}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${instrumentSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
